### ISSUE TITLE
Nats Streaming server server_id is empty in Metrics data  

### ISSUE THREAD

**Issue by codifierr** [nats-io/prometheus-nats-exporter#115]
Nats Endpoint output
**curl** http://localhost:8222/streaming/serverz
**Response :** 
{
  "cluster_id": "test-cluster",
  "server_id": "iZd5VFnDFjeY49HNP8kAiD",
  "version": "0.17.0",
  "go": "go1.13.7",
  "state": "STANDALONE",
  "now": "2020-05-07T14:26:46.098524789Z",
  "start_time": "2020-05-06T08:18:33.001460644Z",
  "uptime": "13h24m6s",
  "clients": 1,
  "subscriptions": 0,
  "channels": 1,
  "total_msgs": 4277,
  "total_bytes": 11579858,
  "in_msgs": 4277,
  "in_bytes": 11892206,
  "out_msgs": 0,
  "out_bytes": 0,
  "open_fds": 20,
  "max_fds": 1048576
}

Metrics endpoint output
# HELP gnatsd_varz_auth_timeout auth_timeout
# TYPE gnatsd_varz_auth_timeout gauge
gnatsd_varz_auth_timeout{server_id=""} 1
# HELP gnatsd_varz_connections connections
# TYPE gnatsd_varz_connections gauge
gnatsd_varz_connections{server_id=""} 4

**Comment by codifierr** [comment]
Fixed with this PR.
https://github.com/nats-io/prometheus-nats-exporter/pull/120

**Comment by likevin97** [comment]
How did you end up resolving this? I'm getting a similar `gnatsd_varz_auth_timeout` issue.
