### ISSUE TITLE
Docker image for aarch64 not provided

### ISSUE THREAD

**Issue by akhenakh** [nats-io/prometheus-nats-exporter#121]
the work is done already https://github.com/nats-io/prometheus-nats-exporter/blob/master/docker/linux/arm64v8/Dockerfile

but the image on hub docker synadia/prometheus-nats-exporter is not multiarch 

see resolved related ticket for drone-server https://github.com/nats-io/nats-server/issues/1540

**Comment by akhenakh** [comment]
also updated the dockerfile for 0.6.2 https://github.com/akhenakh/prometheus-nats-exporter/commit/62dba6397d086dcca60bccaa93b08b604af0e712

**Comment by caleblloyd** [comment]
Fixed in #198 and will be available next release
