### ISSUE TITLE
0.7.0 no docker image

### ISSUE THREAD

**Issue by okgolove** [nats-io/prometheus-nats-exporter#128]
Hello! I am one of maintainers of [prometheus-nats-exporter helm chart](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-nats-exporter).
I'd like to update default version of the exporter using in the chart to 0.7.0 but I can't find new image. Have you changed docker repository name? It used to be synadia/prometheus-nats-exporter.

cc @caarlos0

**Comment by variadico** [comment]
Hey there. Sorry for the delay, we're in the middle of moving our images to a new location.

Going forward, the new images wlil be here:
https://hub.docker.com/r/natsio/prometheus-nats-exporter/tags
