### ISSUE TITLE
Binaries for 0.7.0

### ISSUE THREAD

**Issue by joancafom** [nats-io/prometheus-nats-exporter#129]
Hi,

I have noticed that [the latest tagged release](https://github.com/nats-io/prometheus-nats-exporter/releases/tag/v0.7.0) for Prometheus Nats Exporter (0.7.0) does only include the source code. Usually, previous versions did include the binaries for different platforms and a docker image implementing them (see [0.6.2](https://github.com/nats-io/prometheus-nats-exporter/releases/tag/v0.6.2) for instance)

Will you be updating tagged version 0.7.0 with them too?

**Comment by variadico** [comment]
Yeah, sorry for the delay. Binaries are up now.
https://github.com/nats-io/prometheus-nats-exporter/releases/tag/v0.7.0
