### ISSUE TITLE
Update image on docker hub to 0.7.0 

### ISSUE THREAD

**Issue by marchenkov** [nats-io/prometheus-nats-exporter#132]
Hello,
@wallyqs please add latest release (0.7.0) to docker hub.
https://hub.docker.com/r/synadia/prometheus-nats-exporter/

**Comment by Zyqsempai** [comment]
@wallyqs @variadico Any news on this one?

**Comment by variadico** [comment]
Ah, whoops. We've been moving around where images live recently. This release is available here:
https://hub.docker.com/r/natsio/prometheus-nats-exporter/tags

https://github.com/nats-io/prometheus-nats-exporter#run
