### ISSUE TITLE
Exporter does not register metrics if the first request to NATS fails

### ISSUE THREAD

**Issue by PedroCapdevila** [nats-io/prometheus-nats-exporter#133]
Hi, I updated the exporter from `synadia/prometheus-nats-exporter:0.6.2` to `natsio/prometheus-nats-exporter:0.7.0`. I have the exporter configured to obtain all the metrics of all available NATS and NATS-STREAMING endpoints (varz, connz, channelz, etc.) and, in the new version, the exporter only records metrics from the connz, channelz and serverz endpoints.

I did some tests (with docker-compose) and discovered that the exporter does not record the metrics of the endpoints if the requests to them fail in the first attempt, even if subsequent requests are made and them respond correctly. Obviously, this happens if the exporter starts after NATS service. If the service runs first, all works perfectly.

I'm using the nats container and the nats-exporter container inside a Kubernetes POD. So every time this POD runs, the exporter container starts first (because it initializes faster than NATS), the first requests to NATS fails, and the metrics are not registered as I describe above.

PS: this behaviour doesn't happen in previous versions

**Comment by TomasVojacek** [comment]
Similar happen in version 0.10.1

**Comment by wjordan** [comment]
This was fixed by #273 (released in [v0.14.0](https://github.com/nats-io/prometheus-nats-exporter/releases/tag/v0.14.0)).
