### ISSUE TITLE
gateway_info metrics produce metrics with high label cardinality

### ISSUE THREAD

**Issue by bwerthmann** [nats-io/prometheus-nats-exporter#152]
# Problem

Metrics `gnatsd_gatewayz_inbound_gateway_info` and `gnatsd_gatewayz_outbound_gateway_info` produce  [high label cardinality](https://www.robustperception.io/cardinality-is-key). See [Label Analysis](#label-analysis) for the labels of interest.

# Background

From Prometheus docs on [labels](https://prometheus.io/docs/practices/naming/#labels):

> CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.

# Impact

The impact of this misuse of labels can result in excessive Prometheus storage, poor performance, and excessive billing, overage charges and/or quota exhaustion.

For example, [grafana-cloud](https://grafana.com/docs/grafana-cloud/metrics-prometheus/errors-monitoring/#per-metric-series-limit) limits [`Per-metric series limit`](https://grafana.com/docs/grafana-cloud/metrics-prometheus/errors-monitoring/#per-metric-series-limit) to `20,000`.
> `Per-metric series limit` also known as the max cardinality per metric, or the max number of different label values combinations a single metric can have

`Per-metric series limit` was exceeded in less than 12 hours, and incurred a $900/month overage charge.

# Command and Commit

commit: 436951c4b4ba637a3232776e12b9fd965f4a1f1c
command: `./bin/prometheus-nats-exporter -use_internal_server_id -routez -subz -varz -gatewayz -connz -jsz all -a localhost http://localhost:8222`

# Example Metric: `gnatsd_gatewayz_inbound_gateway_info` 

```console
./prometheus-2.30.3.linux-amd64/promtool query instant --format json 'http://localhost:9090' 'gnatsd_gatewayz_inbound_gateway_info{}' | jq '.[]'
```
```json
{
  "metric": {
    "__name__": "gnatsd_gatewayz_inbound_gateway_info",
    "gateway_name": "gw2",
    "idle": "0s",
    "instance": "localhost:7777",
    "job": "prometheus-nats-exporter",
    "last_activity": "2021-11-10 17:02:14.261993044 +0000 UTC",
    "remote_gateway_name": "gw2",
    "server_id": "N...",
    "start": "2021-11-05 00:10:44.990315695 +0000 UTC",
    "uptime": "5d16h51m29s"
  },
  "value": [
    1636563738.749,
    "0"
  ]
}
```

## 12 hour label counts

The count of values per label from ~12 hours 

```
5 remote_gateway_name
19 start
22 server_id
12725 uptime
21470 last_activity
```

# Example: From a longer running Prometheus server

```bash
for label in last_activity remote_gateway_name server_id start uptime; do curl -sS  http://localhost:9090/api/v1/label/${label}/values | jq -c --arg name "${label}" '{($name): (.data|length)}'; done
```
## 

```json
{"last_activity":1504865}
{"remote_gateway_name":5}
{"server_id":41}
{"start":63}
{"uptime":523781}
```

# Finding Problematic Labels

This one-liner:

1. Gets all the `label` names matching `job="prometheus-nats-exporter"`
2. For each label, gets all label values (scope is all metrics)
3. `jq` out some stats about each label
4. Sort items for convenience 

```bash
curl -sS -d 'match[]={job="prometheus-nats-exporter"}' http://localhost:9090/api/v1/labels | jq -r '.data[]' | while read label; do curl -sS  http://localhost:9090/api/v1/label/${label}/values | jq --arg name "${label}" '{label: $name, count: (.data|length), first: (.data|first), last: (.data|last)}'; done | jq -s '.|sort_by(.count)'
```

```json
[
  {
    "label": "cluster",
    "count": 1,
    "first": "c2",
    "last": "c2"
  },
  {
    "label": "domain",
    "count": 1,
    "first": "test",
    "last": "test"
  },
  {
    "label": "gateway_name",
    "count": 1,
    "first": "gw2",
    "last": "gw2"
  },
  {
    "label": "is_stream_leader",
    "count": 1,
    "first": "true",
    "last": "true"
  },
  {
    "label": "account",
    "count": 2,
    "first": "test-b",
    "last": "test-c"
  },
  {
    "label": "is_meta_leader",
    "count": 2,
    "first": "false",
    "last": "true"
  },
  {
    "label": "meta_leader",
    "count": 2,
    "first": "js-1",
    "last": "js-2"
  },
  {
    "label": "stream_leader",
    "count": 2,
    "first": "js-1",
    "last": "js-2"
  },
  {
    "label": "environment",
    "count": 3,
    "first": "afqdn",
    "last": "ahostname"
  },
  {
    "label": "stream_name",
    "count": 4,
    "first": "s1",
    "last": "s2"
  },
  {
    "label": "remote_gateway_name",
    "count": 5,
    "first": "gw2",
    "last": "gw1"
  },
  {
    "label": "job",
    "count": 6,
    "first": "grafana",
    "last": "otherjob"
  },
  {
    "label": "code",
    "count": 8,
    "first": "200",
    "last": "unknown"
  },
  {
    "label": "instance",
    "count": 11,
    "first": "127.0.0.1:19100",
    "last": "hostname:7777"
  },
  {
    "label": "value",
    "count": 11,
    "first": "2.6.3",
    "last": "server-2"
  },
  {
    "label": "quantile",
    "count": 12,
    "first": "0",
    "last": "1.0"
  },
  {
    "label": "version",
    "count": 15,
    "first": "#100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021",
    "last": "go1.17.2"
  },
  {
    "label": "server_name",
    "count": 20,
    "first": "server-1",
    "last": "server-3"
  },
  {
    "label": "idle",
    "count": 45,
    "first": "0s",
    "last": "9s"
  },
  {
    "label": "cid",
    "count": 52,
    "first": "21",
    "last": "77"
  },
  {
    "label": "server_id",
    "count": 63,
    "first": "N...",
    "last": "http://localhost:8222"
  },
  {
    "label": "start",
    "count": 81,
    "first": "2021-10-28 21:02:04.826267419 +0000 UTC",
    "last": "2021-11-10 20:59:09.736946837 +0000 UTC"
  },
  {
    "label": "__name__",
    "count": 1001,
    "first": "access_evaluation_duration_bucket",
    "last": "up"
  },
  {
    "label": "uptime",
    "count": 524008,
    "first": "0s",
    "last": "9s"
  },
  {
    "label": "last_activity",
    "count": 1507733,
    "first": "2021-11-01 08:00:38.967561211 +0000 UTC",
    "last": "2021-11-10 21:22:49.043662588 +0000 UTC"
  }
]
```

# Label Analysis

Problem labels seem to be:

* `last_activity`
* `uptime`
* `start`
* `idle`

These labels should perhaps be metric values, not labels.

# Workaround

* label drop via Prometheus [metric_relabel_configs](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs). Just discard `last_activity` and `uptime` from metrics with `__name__` of  `gnatsd_gatewayz_inbound_gateway_info` and `gnatsd_gatewayz_outbound_gateway_info`.

**Comment by philipfoulkes** [comment]
I'm happy to submit a PR for this issue. Should we either just remove the _info metrics, or remove the _info metrics and add separate metrics for last_activity, uptime, start, and idle?

Would removal of _info create any compatibility concerns?

@wallyqs

**Comment by bwerthmann** [comment]
@wallyqs are you aware of any consumers of the gateway metrics? I didn't see any gateway metric consumers in the walkthrough/packaged dashboards. Presumably someone is using them?

**Comment by wallyqs** [comment]
@philipfoulkes I think sounds good to clean these metrics up as needed, not sure they are being used since not in dashboards or guides, thanks again for the PR.
