### ISSUE TITLE
JetStream dashboard not working

### ISSUE THREAD

**Issue by manuelottlik** [nats-io/prometheus-nats-exporter#155]
Hey guys,

I am currently setting up my cluster with NATS JetStream using the `nats` and `nack` helm charts which include this prometheus exporter from your [k8s repository](https://github.com/nats-io/k8s). When importing the Grafana dashboards [14862](https://grafana.com/grafana/dashboards/14862), [14725](https://grafana.com/grafana/dashboards/14725) or the one provided in `walkthrough/grafana-jetstream-dash.json` Grafana always spits out the same errors:

`Failed to upgrade legacy queries Datasource named Prometheus was not found`

![screenshot-Google Chrome-NATS JetStream2 - Grafana-202210-081622](https://user-images.githubusercontent.com/28919003/148729766-b849d3f7-21e7-48ec-8e66-5db1cf0acad6.png)

When taking a look inside the JSON of the dashboard definitions it also seems as if there are metrics referenced that do not exist anymore (or not yet?).

Can you tell me what the current state of providing metrics & Grafana dashboard for NATS JetStream is?

Cheers!

**Comment by andy-g** [comment]
Hi @manuelottlik, I contributed the JetStream example dashboard initially (and posted this too [14725](https://grafana.com/grafana/dashboards/14725)), but I'm not a part of the core team, so didn't get a notification of this issue, and just luckily stumbled across it.

From what I can see, the issue is that you don't have a prometheus datasource defined in Grafana, it should look something like this:
![image](https://user-images.githubusercontent.com/557065/151338418-cc17d2c2-bc64-4bdd-9b50-f0373fb57456.png)

Maybe yours is called something different?

I haven't run into the issue, and have just spun up my local environment to check it out, and it's still working fine for me locally. I also re-imported the dashboard from Grafana, specified the datasource and it worked fine (on Grafana 8.3.4).

As you can see below though, you do need to specify your prometheus datasource that contains the NATS & Jetstream metrics.
![image](https://user-images.githubusercontent.com/557065/151339207-c94b8650-1d06-4692-ac18-710857fc1353.png)

**Comment by manuelottlik** [comment]
Hey @andy-g, thanks for the reply!
You are right, there was something wrong with my datasource configuration. However, the dashboard still doesn't work anymore – I guess that is because the names of the metrics changed. Someone actually provided an updated version already – maybe you can add that to the repository / your original dashboard?

https://grafana.com/grafana/dashboards/14862

**Comment by andy-g** [comment]
Hi @manuelottlik glad you're coming right, I realise my local docker had cached an earlier version of the exporter, so I rebuilt my env using the latest version, but my dashboard is still working, when I compare the 2 versions of the dashboard, I see that an example of the change from my version to the other one you reference is below:
<img width="754" alt="image" src="https://user-images.githubusercontent.com/557065/152185704-53c0561c-f3f6-4154-905d-211517655871.png">

But when I bring up an environment with the latest nats-server, prometheus-nats-exporter, and grafana & prometheus, I still get the `gnatsd_varz_jetstream...` version:
![image](https://user-images.githubusercontent.com/557065/152185948-bfe02c1d-15de-43c2-a71d-e51217316df4.png)

What version of the prometheus-nats-exporter are you running?

@variadico I saw that you recently upgraded the dashboard (https://github.com/nats-io/prometheus-nats-exporter/pull/156), I assume it's still working fine for you too? Do you have any idea why there would be a discrepancy between these metric names (`gnatsd_...` to `nats_...` & `jetstream_...` to `nats_...`)?

**Comment by manuelottlik** [comment]
hey @andy-g, I am using the official helm charts "nats" and "nack" from [nats-io/k8s](https://github.com/nats-io/k8s) to deploy my NATS stack. The current version of the "nats" chart (0.12.1) includes the exporter in version 0.9.1 ([see here](https://github.com/nats-io/k8s/blob/v0.12.1/helm/charts/nats/values.yaml#L491)).

**Comment by andy-g** [comment]
@manuelottlik I'm really confused, can you please confirm that if you go to the explore tab in grafana, and start typing `jetsream_stats_stora` you don't see the `gnatsd_varz_jetstream_stats_storage` & `gnatsd_varz_jetstream_stats_reserved_storage` metrics in my screenshot in my previous comment?

I've searched through the `prometheus-nats-exporter` source code, and from what I can see, the `gnatsd` prefix is still used, if you're not seeing that, I'm really confused.  https://github.com/nats-io/prometheus-nats-exporter/blob/ff211d57e4025fd55a2d14503210831b2a5de52a/collector/collector.go#L33  

The other change between my dashboard and the other one, is that the `jetream...` metrics have been renamed to `nats...`, so may be worth checking if you have these in the explore page too:
<img width="634" alt="image" src="https://user-images.githubusercontent.com/557065/152516045-4f9f47d1-582a-47b9-bc8b-9ca08a7f9166.png">

**Comment by manuelottlik** [comment]
@andy-g here you go:

![screenshot-Google Chrome-Explore - Prometheus - Grafana-202204-220340](https://user-images.githubusercontent.com/28919003/152602825-4e7c173c-0424-4be1-b5ab-8bd00a6538f2.png)
![screenshot-Google Chrome-Explore - Prometheus - Grafana-202204-220414](https://user-images.githubusercontent.com/28919003/152602849-00f4103f-17a0-4c95-ac75-0bdcc2f84032.png)
![screenshot-Google Chrome-Explore - Prometheus - Grafana-202204-220458](https://user-images.githubusercontent.com/28919003/152602968-11177545-092d-465d-98df-9367c01fb038.png)

**Comment by manuelottlik** [comment]
Oh I think I found it: In [this line](https://github.com/nats-io/prometheus-nats-exporter/blob/v0.9.1/collector/collector.go#L30) it says that they leave `gnatsd` so people don't have to update their dashboards (lol), but in the helm chart in [this line](https://github.com/nats-io/k8s/blob/main/helm/charts/nats/templates/statefulset.yaml#L574) they overwrite the prefix.

**Comment by andy-g** [comment]
Very nice find @manuelottlik, having inconsistent metrics depending on whether you bring it up locally (or in docker) or via helm doesn't make it simple to create a shared dashboard. Not sure if a variable on the grafana import would be able to solve this, I'll have to take a look.

Otherwise, on the dashboard readme we could just include instructions to use the same command that Helm is using.

**Comment by manuelottlik** [comment]
Yes, I feel like this issue is best solved by just providing clarity in each projects README about what is going on — if the future versions of the exporter are going to make the `nats_` prefix the default for metrics though, it might as well make sense to simply update the dashboard overall and release it as a separate one / just link to the existing one I mentioned earlier.

**Comment by andy-g** [comment]
@manuelottlik I've added a note on the [Grafana.com template](https://grafana.com/grafana/dashboards/14725), and opened a PR to include a note regarding the HELM prefix override on the walkthrough README, as well as a helm specific version of the template #161.

**Comment by manuelottlik** [comment]
Awesome!

**Comment by variadico** [comment]
Does the helm dashboard in #161 solve your issue, @manuelottlik?

**Comment by manuelottlik** [comment]
Yes it does, I think this issue can be closed now. Thanks again, @andy-g !
