### ISSUE TITLE
Won't run as windows service

### ISSUE THREAD

**Issue by JohannesEH** [nats-io/prometheus-nats-exporter#164]
Hi I'm trying to get v0.9.1 to run as a windows service but it fails with a 7009 (timeout) error. Watching the logs, the server starts up fine but the seems to be some miscommunication between the windows service control manager and the prometheus-nats-exporter process that makes it think the process hasn't started.

Do you have any ideas how to solve this?

**Comment by jasase** [comment]
I have the same problem. Seems that it is not compatible with windows services. Currently running it with https://nssm.cc/

**Comment by JohannesEH** [comment]
Yeah, ended up doing the same.
