### ISSUE TITLE
Expose exporters collectors

### ISSUE THREAD

**Issue by nikakis** [nats-io/prometheus-nats-exporter#174]
I would like to expose the collectors field from exporter [here](https://github.com/nats-io/prometheus-nats-exporter/blob/main/exporter/exporter.go#L75) and also the `initializeCollectors` function [here](https://github.com/nats-io/prometheus-nats-exporter/blob/main/exporter/exporter.go#L168) and `clearCollectors` function for the sake of this [feature](https://github.com/grafana/agent/issues/1704)? 
Does this makes sense to you?
Thanks!

**Comment by wallyqs** [comment]
sorry for the delay just merged your PR, thanks for the contribution!
