### ISSUE TITLE
Tag available for version 0.9.3, but not Release

### ISSUE THREAD

**Issue by carrodher** [nats-io/prometheus-nats-exporter#177]
There is a tag available for the new version (0.9.3) at https://github.com/nats-io/prometheus-nats-exporter/releases/tag/v0.9.3, but there is not a release entry in the [Releases view](https://github.com/nats-io/prometheus-nats-exporter/releases).

Do you have plans to release this new version like the previous ones?

**Comment by wallyqs** [comment]
Thanks @carrodher , the release is available now: https://github.com/nats-io/prometheus-nats-exporter/releases/tag/v0.9.3
