### ISSUE TITLE
Release for 0.10.0 version

### ISSUE THREAD

**Issue by carrodher** [nats-io/prometheus-nats-exporter#186]
Thanks for the new version released a couple of days ago.
I just saw this version appears as a tag at https://github.com/nats-io/prometheus-nats-exporter/releases/tag/v0.10.0 but there is not an associated release at https://github.com/nats-io/prometheus-nats-exporter/releases.
Could you please create the associated release?

**Comment by wallyqs** [comment]
It should be fixed now, thanks for raising the issue

**Comment by carrodher** [comment]
Thank you very much!
