### ISSUE TITLE
gnatsd This dhashboard is out of date

### ISSUE THREAD

**Issue by Doslin** [nats-io/prometheus-nats-exporter#188]
https://github.com/nats-io/prometheus-nats-exporter/blob/main/walkthrough/grafana-nats-dash.json
the dashboard

**Comment by countravioli** [comment]
@Doslin - I think I just came across this too.Does it have to do with all the variable names being different? This is my first attempt at using grafana and my observation is that nats_server variable names have changed from something like `gnatsd_varz_in_msgs` to `nats_varz_in_msgs` and jetstream messages have changed in various ways as well.

Just wanted a sanity check and to add some details to this ticket if it was closed without enough info maybe
