### ISSUE TITLE
Publish new release

### ISSUE THREAD

**Issue by liam-verta** [nats-io/prometheus-nats-exporter#217]
It's been several months and number of updates have been merged including vulnerability remediations.  Please cut a new release. Thanks!

**Comment by caleblloyd** [comment]
cc @wallyqs

**Comment by liam-verta** [comment]
@samuelattwood
Would you be able to do this?

**Comment by samuelattwood** [comment]
Hey @liam-verta - [v0.11.0](https://github.com/nats-io/prometheus-nats-exporter/releases/tag/v0.11.0) has been published

We will be following a more regular cadence going forward to keep dependencies updated. Thanks!
