### ISSUE TITLE
Leaked credentials at the `server_id` label

### ISSUE THREAD

**Issue by frodenas** [nats-io/prometheus-nats-exporter#22]
When the nats `url` contains a `user` and `password` (because nats server authentication is enabled), credentials are reported as part of the metric `server_id` label. It's true that we can specify a `tag` to override the nats `url` at the `server_id` label, but in my particular use case I want to report the nats url and not a tag, and I don't want to expose my credentials.

**Comment by ColinSullivan1** [comment]
@frodenas , thank you for using NATS, and reporting the issue!  Good catch; we should strip out credentials from the url.  I'll look into this.  As you suggested, using tags would be a workaround in the meantime - you could even use your url w/o credentials as the tag.
