### ISSUE TITLE
missing gnatsd_varz_cpu, is nats.io does not have jetstream ready while exporter start

### ISSUE THREAD

**Issue by tvojacek** [nats-io/prometheus-nats-exporter#242]
Almost all metrics are missing is 
if nats.io recover jetstream for too long
while nats expoter start.

reproduce
kill nats.io with big jetstream (300GB)
start nats.io
start nats exporter
wait 5>minutes will nats.io recover jetstream and finish start
check metrics most of metrics are missing.

**Comment by joonas-fi** [comment]
Duplicate of #133 ?
