### ISSUE TITLE
Include username in detailed connection information.

### ISSUE THREAD

**Issue by ebusto** [nats-io/prometheus-nats-exporter#275]
### What motivated this proposal?

Our NATS cluster has a very small number of accounts, but each account has a number of distinct users. Being able to track traffic by user would be helpful when identifying heavy hitters.

### What is the proposed change?

When collecting detailed connection information (when cardinality is already out the window), add `auth=true` as a query parameter when hitting the `connz` endpoint, and include the `name_tag` value in each corresponding metric.

### Who benefits from this change?

Any NATS operator that wishes to track metrics per user, rather than (or in addition to) per account.

### What alternatives have you evaluated?

Unfortunately splitting out our users into separate accounts would be a significant (breaking) change. I suspect we're not alone.

**Comment by robinbowes** [comment]
@ebusto @wallyqs Was this fixed by #276 ?

**Comment by ebusto** [comment]
Yes, this issue should be closed.

**Comment by robinbowes** [comment]
Thanks.
