### ISSUE TITLE
build error: cannot load crypto/ecdh: malformed module path "crypto/ecdh": ...

### ISSUE THREAD

**Issue by ivanix1** [nats-io/prometheus-nats-exporter#296]
### What version were you using?

latest main branch
error when trying to run "make build" as per README.md instructions.

### What environment was the server running in?

ubuntu 24.04
go version
go version go1.13.8 linux/amd64

### Is this defect reproducible?

100%

### Given the capability you are leveraging, describe your expectation?

would like the code to build without errors

### Given the expectation, what is the defect you are observing?

build github.com/nats-io/prometheus-nats-exporter: cannot load crypto/ecdh: malformed module path "crypto/ecdh": missing dot in first path element

**Comment by Jarema** [comment]
The project requires `go 1.21`, and you're running a really old `1.13`.

Please upgrade and let us know if it fixes the issue.
I cannot reproduce it.
