### ISSUE TITLE
Add "Number of Subjects" Metric

### ISSUE THREAD

**Issue by tkeller-moxe** [nats-io/prometheus-nats-exporter#312]
### What motivated this proposal?

We would like to track and create alerts on the number of subjects on a stream.
Something in our infrastructure has been having this not correctly correlate with the number of messages on a stream and it grows exponentially causing a memory leak. We would like to be able to monitor this for future regression and action. 

### What is the proposed change?

 This Metric is available on the JSZ endpoint we would like this to be exported as a Prometheus metric. 

### Who benefits from this change?

NATs System Administrators and SMEs can leverage this datapoint to monitor system behavior from a single pane of glass instead of a CLI tool here or a webpage there. 

### What alternatives have you evaluated?

I can get this metric via the CLI or the web API myself. This is just the correct place to export it.

**Comment by Jarema** [comment]
We can definately add this metric.

Are you interested in contributing it?

**Comment by tkeller-moxe** [comment]
I was looking into contributing it but realized my knowledge of GO is substantially lacking. So I figured it made more sense to raise a request instead😅

**Comment by Jarema** [comment]
No worries :). 

We will work on that soon.

**Comment by tkeller-moxe** [comment]
Thank you! :D
