### ISSUE TITLE
Not collecting metrics for all servers using a headless service

### ISSUE THREAD

**Issue by GRVYDEV** [nats-io/prometheus-nats-exporter#313]
### What version were you using?

nats-server: v2.10.20

### What environment was the server running in?

Kubernetes using this docker image nats:2.10.20-alpine

### Is this defect reproducible?

Yes

### Given the capability you are leveraging, describe your expectation?

I was expecting the exporter to collect aggregate metrics for the whole cluster however things such as cpu, memory and connection counts are only for the server instance it connects to.

### Given the expectation, what is the defect you are observing?

When giving the prometheus exporter a headless service in kubernetes I would expect it to collect metrics from all of the IP addresses returned from that headless service. Instead it only returns the metrics for the single instance.

**Comment by Jarema** [comment]
According to [official guidelines](https://prometheus.io/docs/instrumenting/writing_exporters/#deployment), you should run exactly one exporter per instance:

> Each exporter should monitor exactly one instance application, preferably sitting right beside it on the same machine.

**Comment by GRVYDEV** [comment]
Hey Jarema thanks for the response! I deduced that after reading through some of the source code. Thanks for the help!
