### ISSUE TITLE
Add TYPES and HELP headers

### ISSUE THREAD

**Issue by jarretlavallee** [nats-io/prometheus-nats-exporter#315]
### What motivated this proposal?

The metrics are currently untyped and missing headers. Including these would be helpful with standard Prometheus scrapers and our solutions like Datadog's OpenMetrics integration.

### What is the proposed change?

Please add types to the metrics as well as `# HELP` headers with descriptions of the metrics. 

### Who benefits from this change?

Any user trying to understand the output of the metrics using standard Prometheus scraping software.

**Comment by mtmk** [comment]
thanks for the proposal @jarretlavallee just having a quick look they all seem to have TYPE but a lot don't have meaningful help text even though HELP is there as well. it that the main concern most don't have proper help text?

e.g.:
```
# HELP gnatsd_connz_in_bytes in_bytes
# TYPE gnatsd_connz_in_bytes counter
gnatsd_connz_in_bytes{server_id="http://localhost:8222"} 37
# HELP gnatsd_connz_in_msgs in_msgs
# TYPE gnatsd_connz_in_msgs counter
gnatsd_connz_in_msgs{server_id="http://localhost:8222"} 1
```

I'm new to this stuff so I might be missing something. could you give me a few examples please?

**Comment by jarretlavallee** [comment]
@mtmk You are correct. I opened this in the wrong repo as this is a surveyor issue.
