### ISSUE TITLE
Zipkin like tracing

### ISSUE THREAD

**Issue by rohitpal99** [nats-io/prometheus-nats-exporter#34]
Is it possible to get zipkin like tracing into Prometheus from exporter.

Please suggest.

**Comment by ColinSullivan1** [comment]
Would you mind explaining your use case further?   Are you suggesting zipkin integration into the NATS server or NATS streaming server?

**Comment by rohitpal99** [comment]
Sure,
Thanks for replying back.
I would like the tracing of a request throughout my   application, So that I could know what flow has a request taken through the microservices application which could include information also on what NATS subjects were visited.
Also it would be great if we would trace NATS requests per subject like throughout, How many failed etc.

**Comment by abbi-gaurav** [comment]
I agree having Zipkin like tracing would sure be helpful especially for troubleshooting scenarios.
e.g. the trace of message 
 publishing ----> [NATS Streaming] -----> Consumer 1
                                                            ------> Consumer 2
                                                            ------> Consumer n
can help me tell if there are any consumers or not for a particular message.

However, I suppose might be other possibilities to get similar information.

**Comment by wallyqs** [comment]
Closing for now. For zipkin like tracing can check: https://github.com/nats-io/not.go

**Comment by saggzz** [comment]
Seems like  https://github.com/nats-io/not.go is not maintained anymore. Tried this in Java and Maven dependency is not available anymore.

**Comment by ripienaar** [comment]
We are working on this as part of nats-surveyor where it will support tracing across imports. Some detail:

 * ADR https://github.com/nats-io/nats-server/blob/master/doc/adr/0003-distributed-tracing.md
 * full multi component overview https://gist.github.com/ripienaar/81dcd435b9bcb34419a7caec8e52c2b8
