### ISSUE TITLE
Support nats-streaming server metrics

### ISSUE THREAD

**Issue by mitchhh22** [nats-io/prometheus-nats-exporter#37]
I'm looking for a solution to monitoring the /streaming metrics exposed by a nats-streaming server.

For example: http://localhost:8222/streaming/clientsz?limit=1&offset=1&subs=1

Specifically it would be great to have prometheus scrape the `pending_count` metric for each subscription. Trying to monitor this currently yields a skewed result due to the many messages in/out between nodes in the nats-streaming cluster that aren't from connected clients.

**Comment by ColinSullivan1** [comment]
@mitchhh22 , This sounds good, and I agree that we should include streaming metrics in the prometheus monitor.  We'll look into it.

**Comment by wallyqs** [comment]
This was supported via #54
