### ISSUE TITLE
Support streaming channel and subscription metrics

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/prometheus-nats-exporter#39]
In NATS Streaming monitoring provide metrics for channels and subscriptions.

Also referenced here:  https://groups.google.com/forum/#!topic/natsio/RCACO14-_aM

**Comment by activeshadow** [comment]
This is a critical roadblock for me using NATS Streaming in my production environment. I don't mind contributing to this effort, assuming someone can point me in the right direction.

I assume all or part of [this issue thread](https://github.com/nats-io/nats-streaming-server/issues/491) will be relevant to the effort... can we get a conversation started around this?

**Comment by ColinSullivan1** [comment]
@activeshadow , for sure, and thank you for starting this conversation!  We would welcome a contribution!

To start, one item that needs to be addressed is how to best handle arrays of JSON objects for Prometheus scraping.  As an arbitrary example, let's say we wanted to return the client id for subscription "foo" in the example JSON returned below for `clientsz`:

```{
  "cluster_id": "test-cluster",
  "server_id": "J3Odi0wXYKWKFWz5D5uhH9",
  "now": "2017-06-07T14:48:06.157468748+02:00",
  "offset": 1,
  "limit": 1,
  "count": 1,
  "total": 11,
  "clients": [
    {
      "id": "benchmark-sub-0",
      "hb_inbox": "_INBOX.jAHSY3hcL5EGFQGYmfayQK",
      "subscriptions": {
        "foo": [
          {
            "client_id": "benchmark-sub-0",
            "inbox": "_INBOX.jAHSY3hcL5EGFQGYmfayvC",
            "ack_inbox": "_INBOX.J3Odi0wXYKWKFWz5D5uhem",
            "is_durable": false,
            "is_offline": false,
            "max_inflight": 1024,
            "ack_wait": 30,
            "last_sent": 505597,
            "pending_count": 0,
            "is_stalled": false
          }
        ]
      }
    }
  ]
}
```

The naming [style guide](https://prometheus.io/docs/practices/naming/) in Prometheus  would suggest that this field be named something like: `nss_clients_subscriptions_foo_client_id`

I'm thinking that another delimiter (maybe `/`?) would be better to look at because underscores are used in our field names.  e.g:
`nss/clients/subscriptions/foo/client_id`.  

_Caveat:  I don't know if that delimiter will work with Prometheus and Grafana._

Implementation-wise, I would look into at making [this loop](https://github.com/nats-io/prometheus-nats-exporter/blob/v0.1.0/collector/collector.go#L187) into a function to recurse into and append the object name to the subsystem param for JSON objects.

What do you think?  We're always open to new and better ideas...

CC @kozlovic @wallyqs

**Comment by ColinSullivan1** [comment]
Related to #7 and #37

**Comment by marceldegraaf** [comment]
I'm evaluating NATS (and Streaming) for a production deployment. Having proper Prometheus metrics would be great; let me know if I can help.

**Comment by ColinSullivan1** [comment]
@activeshadow , Great suggestion about using labels.  It will be more code, but also much more useful.

`last_seq` - `last sent` is a good indicator.

`subscriptions.pending_count` will give you the number of outstanding acknowledgments - the number of messages sent to your subscriber that have not been acknowledged.  If you process in your callback and auto acknowledge, or manually acknowledge after processing your message, this value may be a good indicator of how well your application is keeping up.  If the value consistently remains very close to `"max_inflight"` you are not keeping up and it's probably time to scale.  This may be too granular though for a higher level view, and if `"max_inflight"` has been configured to be a low value, this'll be less useful.

@kozlovic would `"subscriptions.pending_count"` be accurate/consistent enough?

**Comment by ColinSullivan1** [comment]
@marceldegraaf , we'd welcome a contribution in this area.  Would you want to look over the code and write up a short proposal in this issue?

**Comment by kozlovic** [comment]
@ColinSullivan1 Yes, `pending_count` means what you described: the number of messages sent by the server to the subscription for which corresponding acknowledgments have not been received (or processed) yet.

**Comment by marceldegraaf** [comment]
@ColinSullivan1 can you let me know what you'd expect of such a proposal? I'm new to the NATS codebase and the project in general.

**Comment by ColinSullivan1** [comment]
@marceldegraaf , Apologies for the delay, @wallyqs will take at look.

**Comment by caarlos0** [comment]
BTW, I've opened a PR with some metrics: #54

**Comment by seriousben** [comment]
We are using #54 and it works well for us btw. Would be nice to get that PR closer to being merged.

**Comment by alexellis** [comment]
Hey @ColinSullivan1 @wallyqs what do you think of #54? We have users in production who could really benefit from this too.

Thanks,

Alex

**Comment by JensRantil** [comment]
https://github.com/nats-io/prometheus-nats-exporter/pull/54 is now merged so maybe this can be closed?

**Comment by JensRantil** [comment]
> #54 is now merged so maybe this can be closed?

@ColinSullivan1 Ping.

**Comment by ColinSullivan1** [comment]
@JensRantil - Thank you - yes, Wally closed it.
