### ISSUE TITLE
Is there a helm chart for this?

### ISSUE THREAD

**Issue by juandiegopalomino** [nats-io/prometheus-nats-exporter#60]
Just wondering if you guys implemented one officially.

**Comment by wallyqs** [comment]
Not for the nats exporter repo itself but a user contributed one for the helm chart from the nats operator so that it can be enabled through that here (`metrics.enabled`):
https://github.com/nats-io/nats-operator/tree/master/helm/nats-operator#nats-operator-helm-chart

**Comment by juandiegopalomino** [comment]
thank you!
