### ISSUE TITLE
no artifacts uploaded to the release

### ISSUE THREAD

**Issue by caarlos0** [nats-io/prometheus-nats-exporter#63]
https://github.com/nats-io/prometheus-nats-exporter/releases/tag/v0.2.0

seems like the release process failed somehow?

cc/ @wallyqs

**Comment by wallyqs** [comment]
Not sure how it failed when pushing v0.2.0 but this did not occur for v0.2.2... https://github.com/nats-io/prometheus-nats-exporter/releases/tag/v0.2.2

**Comment by caarlos0** [comment]
yeah, its good! thanks!
