### ISSUE TITLE
An error has occurred during metrics gathering

### ISSUE THREAD

**Issue by JohnnyQQQQ** [nats-io/prometheus-nats-exporter#67]
After updating our stateful set in kubernetes the exporter stopped working with the following error:

```log
An error has occurred during metrics gathering:

3 error(s) occurred:
* collected metric nss_chan_subs_last_sent label:<name:"channel" value:"shop.feature.disabled" > label:<name:"client_id" value:"" > label:<name:"server" value:"http://localhost:8222" > gauge:<value:353 >  was collected before with the same name and label values
* collected metric nss_chan_subs_pending_count label:<name:"channel" value:"shop.feature.disabled" > label:<name:"client_id" value:"" > label:<name:"server" value:"http://localhost:8222" > gauge:<value:0 >  was collected before with the same name and label values
* collected metric nss_chan_subs_max_inflight label:<name:"channel" value:"shop.feature.disabled" > label:<name:"client_id" value:"" > label:<name:"server" value:"http://localhost:8222" > gauge:<value:1024 >  was collected before with the same name and label values
```

We are running nats-streaming v0.14.0 with the exporter as sidecar.

**Comment by wallyqs** [comment]
Thanks for the report, looks like this might be the same issue that was fixed via https://github.com/nats-io/prometheus-nats-exporter/pull/65
Will push a new release with the fix today, sorry about that.

**Comment by JohnnyQQQQ** [comment]
Thank you, didn't checked the MRs. Will reopen if the problem persists after the new release.

**Comment by JohnnyQQQQ** [comment]
@wallyqs when will the new release approximately land?

**Comment by wallyqs** [comment]
Sorry for the delay here, have pushed a new version of the exporter where this should be fixed: https://github.com/nats-io/prometheus-nats-exporter/releases/tag/v0.2.2
