### ISSUE TITLE
Incorrect Nats Streaming Metrics Types

### ISSUE THREAD

**Issue by juandiegopalomino** [nats-io/prometheus-nats-exporter#68]
Going to localhost:7777/metrics, the nss_server_bytes_total proclaims itself to be a counter
```
# HELP nss_server_bytes_total Total of bytes
# TYPE nss_server_bytes_total counter
```
And yet it can actually go down as messages are deleted from the servers due to old age (which is expected)
<img width="1583" alt="Screen Shot 2019-04-19 at 12 40 05 PM" src="https://user-images.githubusercontent.com/10430635/56433911-8eb49700-62a0-11e9-8ad3-03d24deb5130.png">
Am I doing something silly or are the metric types weird (and if they are weird, there might be others)?

**Comment by wallyqs** [comment]
OK so we should change this into a gauge then: https://prometheus.io/docs/concepts/metric_types/

**Comment by caarlos0** [comment]
check #76 

sorry about my mistake on it.
