### ISSUE TITLE
QUESTION Is posible to add custom metrics prefix or custom label?

### ISSUE THREAD

**Issue by castocolina** [nats-io/prometheus-nats-exporter#86]
My dev-ops team manage the central prometheus and use configuration that requires we provide custom match prefix for my components metrics. My dev team need to set custom prefix for all our products components. Is possible do this for the exporter or set custom label?

**Comment by wallyqs** [comment]
@castocolina there is a wip PR for this here: https://github.com/nats-io/prometheus-nats-exporter/pull/64 will see if I can pick it it up and merge, and then ship in next release

**Comment by wallyqs** [comment]
Fixed via #64
